id: I7646AACA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T20:47:28+00:00'
last_modified: '2022-06-07T12:25:17.816397+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG655
  title: གསར་བསྒྱུར་རཱ་མ་ཡཱ་ཎའི་རྟོགས་བརྗོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    34B8:
      image_group_id: I1KG1219
      title: ''
      total_pages: 316
      order: 1
      base_file: 34B8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
